import random
import datetime
#amountOfOrders = int(input('Enter how many orders to generate: '))
#averageValue = float(input('Enter average value of order: '))
#standardDev = float(input('Enter standard deviation'))
fileName = input('Enter name for sql file: ')

with open(fileName, 'w') as f:
	
	#Generates 200 orders per day of 2023 placed at random times
	oId = 1
	day1 = datetime.date(2023, 1, 1)
	dayDelta = datetime.timedelta(days=1)
	f.write("INSERT INTO Customer_Orders (order_number, total_cost, order_time, order_date) VALUES ")
	for i in range(0,365):
		inputDate = day1 + i*dayDelta
		for j in range(0, 199):
			inputTime = datetime.time(random.randrange(8, 21), random.randrange(0, 59), random.randrange(0, 59))
			inputTimeString = inputTime.strftime('%H:%M:%S')
			inputDateString = inputDate.strftime('%Y-%m-%d')
			f.write("('" + str(oId) + "', '0', '" + inputTimeString + "', '" + inputDateString + "'),\n")
			oId += 1
	inputDate = day1 + 365*dayDelta
	for j in range(0,198):
		inputTime = datetime.time(random.randrange(8, 21), random.randrange(0, 59), random.randrange(0, 59))
		inputTimeString = inputTime.strftime('%H:%M:%S')
		inputDateString = inputDate.strftime('%Y-%m-%d')
		f.write("('" + str(oId) + "', '0', '" + inputTimeString + "', '" + inputDateString + "'),\n")
		oId += 1
	
	inputTime = datetime.time(random.randrange(8, 21), random.randrange(0, 59), random.randrange(0, 59))
	inputTimeString = inputTime.strftime('%H:%M:%S')
	inputDateString = inputDate.strftime('%Y-%m-%d')
	f.write("('" + str(oId) + "', '0', '" + inputTimeString + "', '" + inputDateString + "');\n")
	oId += 1
	#Generates Customer_Order_Details that lists order contents.  Each order is one of 3 different orders.  Also tracks total price of order
	orderTypeList = []
	f.write("INSERT INTO Customer_Order_Details (menu_item, order_number, quantity) VALUES ")
	for i in range(1, oId-1):
		orderType = random.randrange(0, 14)
		menuItemString = []
		menuItemStringQuant = []
		if orderType == 0:
			menuItemString.append("Cheeseburger")
			menuItemString.append("3 Chicken Tenders")
			menuItemStringQuant.append("2")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			#f.write("UPDATE Customer_Orders SET TotalCost = '18.77' WHERE CustomerID = '" + str(i) + "';\n")
			orderTypeList.append(orderType)
		elif orderType == 1:
			menuItemString.append("Aggie Chicken Club")
			menuItemString.append("French Fries")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("2")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			#f.write("UPDATE Customer_Orders SET TotalCost = '12.37' WHERE CustomerID = '" + str(i) + "';\n")
			orderTypeList.append(orderType)
		elif orderType == 2:
			menuItemString.append("Cheeseburger")
			menuItemString.append("French Fries")
			menuItemString.append("Vanilla Aggie Shake")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			#f.write("UPDATE Customer_Orders SET TotalCost = '13.37' WHERE CustomerID = '" + str(i) + "';\n")
			orderTypeList.append(orderType)
		elif orderType == 3:
			menuItemString.append("Tuna Melt")
			menuItemString.append("Root Beer Float")
			menuItemString.append("Fish Sandwich")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			orderTypeList.append(orderType)
		elif orderType == 4:
			menuItemString.append("Black Bean Burger")
			menuItemString.append("Chicken Caesar Salad")
			menuItemString.append("20 OZ Aquafina Water")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			orderTypeList.append(orderType)
		elif orderType == 5:
			menuItemString.append("Gig Em Patty Melt")
			menuItemString.append("Sugar Cookie Oreo Cookie Ice Cream Sundae")
			menuItemString.append("Revs Grilled Chicken Sandwich")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			orderTypeList.append(orderType)
		elif orderType == 6:
			menuItemString.append("20 OZ Fountain Drink")
			menuItemString.append("2 Corn Dogs")
			menuItemString.append("Strawberry Aggie Shake")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			orderTypeList.append(orderType)
		elif orderType == 7:
			menuItemString.append("16 OZ Aquafina Water")
			menuItemString.append("Spicy Chicken Sandwich")
			menuItemString.append("1 Chicken Bacon Ranch Wrap")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			orderTypeList.append(orderType)
		elif orderType == 8:
			menuItemString.append("Oreo Cookie Double Scoop Ice Cream")
			menuItemString.append("Vanilla Double Scoop Ice Cream")
			menuItemString.append("Strawberry Double Scoop Ice Cream")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			orderTypeList.append(orderType)
		elif orderType == 9:
			menuItemString.append("Chocolate Double Scoop Ice Cream")
			menuItemString.append("Chocolate Chip Cookie Oreo Cookie Ice Cream Sundae")
			menuItemString.append("Chocolate Chip Cookie Vanilla Ice Cream Sundae")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			orderTypeList.append(orderType)
		elif orderType == 10:
			menuItemString.append("Chocolate Chip Cookie Strawberry Ice Cream Sundae")
			menuItemString.append("Chocolate Chip Cookie Chocolate Ice Cream Sundae")
			menuItemString.append("Sugar Cookie Vanilla Ice Cream Sundae")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			orderTypeList.append(orderType)
		elif orderType == 11:
			menuItemString.append("Sugar Cookie Strawberry Ice Cream Sundae")
			menuItemString.append("Sugar Cookie Chocolate Ice Cream Sundae")
			menuItemString.append("Oreo Cookie Aggie Shake")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			orderTypeList.append(orderType)
		elif orderType == 12:
			menuItemString.append("Chocolate Aggie Shake")
			menuItemString.append("1 Classic Chicken Wrap")
			menuItemString.append("2 Classic Chicken Wraps")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			orderTypeList.append(orderType)
		elif orderType == 13:
			menuItemString.append("2 Chicken Bacon Ranch Wraps")
			menuItemString.append("2 Hot Dogs")
			menuItemString.append("Classic Hamburger")
			menuItemString.append("Bacon Cheeseburger")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			f.write("('" + str(menuItemString[3]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[3]) + "'),\n")
			orderTypeList.append(orderType)

	orderType = random.randrange(0, 14)
	menuItemString = []
	menuItemStringQuant = []
	if orderType == 0:
		menuItemString.append("Cheeseburger")
		menuItemString.append("3 Chicken Tenders")
		menuItemStringQuant.append("2")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[1]) + "');\n")
		#f.write("UPDATE Customer_Orders SET TotalCost = '18.77' WHERE CustomerID = '" + str(i) + "';\n")
		orderTypeList.append(orderType)
	elif orderType == 1:
		menuItemString.append("Aggie Chicken Club")
		menuItemString.append("French Fries")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("2")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[1]) + "');\n")
		#f.write("UPDATE Customer_Orders SET TotalCost = '12.37' WHERE CustomerID = '" + str(i) + "';\n")
		orderTypeList.append(orderType)
	elif orderType == 2:
		menuItemString.append("Cheeseburger")
		menuItemString.append("French Fries")
		menuItemString.append("Vanilla Aggie Shake")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[2]) + "');\n")
		#f.write("UPDATE Customer_Orders SET TotalCost = '13.37' WHERE CustomerID = '" + str(i) + "';\n")
		orderTypeList.append(orderType)
	elif orderType == 3:
		menuItemString.append("Tuna Melt")
		menuItemString.append("Root Beer Float")
		menuItemString.append("Fish Sandwich")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[2]) + "');\n")
		orderTypeList.append(orderType)
	elif orderType == 4:
		menuItemString.append("Black Bean Burger")
		menuItemString.append("Chicken Caesar Salad")
		menuItemString.append("20 OZ Aquafina Water")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[2]) + "');\n")
		orderTypeList.append(orderType)
	elif orderType == 5:
		menuItemString.append("Gig Em Patty Melt")
		menuItemString.append("Sugar Cookie Oreo Cookie Ice Cream Sundae")
		menuItemString.append("Revs Grilled Chicken Sandwich")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[2]) + "');\n")
		orderTypeList.append(orderType)	
	elif orderType == 6:
		menuItemString.append("20 OZ Fountain Drink")
		menuItemString.append("2 Corn Dogs")
		menuItemString.append("Strawberry Aggie Shake")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[2]) + "');\n")
		orderTypeList.append(orderType)
	elif orderType == 7:
		menuItemString.append("16 OZ Aquafina Water")
		menuItemString.append("Spicy Chicken Sandwich")
		menuItemString.append("1 Chicken Bacon Ranch Wrap")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[2]) + "');\n")
		orderTypeList.append(orderType)
	elif orderType == 8:
		menuItemString.append("Oreo Cookie Double Scoop Ice Cream")
		menuItemString.append("Vanilla Double Scoop Ice Cream")
		menuItemString.append("Strawberry Double Scoop Ice Cream")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[2]) + "');\n")
		orderTypeList.append(orderType)
	elif orderType == 9:
		menuItemString.append("Chocolate Double Scoop Ice Cream")
		menuItemString.append("Chocolate Chip Cookie Oreo Cookie Ice Cream Sundae")
		menuItemString.append("Chocolate Chip Cookie Vanilla Ice Cream Sundae")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[2]) + "');\n")
		orderTypeList.append(orderType)
	elif orderType == 10:
		menuItemString.append("Chocolate Chip Cookie Strawberry Ice Cream Sundae")
		menuItemString.append("Chocolate Chip Cookie Chocolate Ice Cream Sundae")
		menuItemString.append("Sugar Cookie Vanilla Ice Cream Sundae")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[2]) + "');\n")
		orderTypeList.append(orderType)
	elif orderType == 11:
		menuItemString.append("Sugar Cookie Strawberry Ice Cream Sundae")
		menuItemString.append("Sugar Cookie Chocolate Ice Cream Sundae")
		menuItemString.append("Oreo Cookie Aggie Shake")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[2]) + "');\n")
		orderTypeList.append(orderType)
	elif orderType == 12:
		menuItemString.append("Chocolate Aggie Shake")
		menuItemString.append("1 Classic Chicken Wrap")
		menuItemString.append("2 Classic Chicken Wraps")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[2]) + "');\n")
		orderTypeList.append(orderType)
	elif orderType == 13:
		menuItemString.append("2 Chicken Bacon Ranch Wraps")
		menuItemString.append("2 Hot Dogs")
		menuItemString.append("Classic Hamburger")
		menuItemString.append("Bacon Cheeseburger")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
		f.write("('" + str(menuItemString[3]) + "', '" + str(oId-1) + "', '" + str(menuItemStringQuant[3]) + "');\n")
		orderTypeList.append(orderType)

	#Generates two very high traffic days
	f.write("INSERT INTO Customer_Orders (order_number, total_cost, order_time, order_date) VALUES ")
	for i in range(0, 799):
		inputDate = datetime.date(2023, 1, 16)
		inputDateString = inputDate.strftime('%Y-%m-%d')
		inputTime = datetime.time(random.randrange(8, 21), random.randrange(0, 59), random.randrange(0, 59))
		inputTimeString = inputTime.strftime('%H:%M:%S')
		f.write("('" + str(oId) + "', '0', '" + inputTimeString + "', '" + inputDateString + "'),\n")
		oId +=1

	inputDate = datetime.date(2023, 1, 16)
	inputDateString = inputDate.strftime('%Y-%m-%d')
	inputTime = datetime.time(random.randrange(8, 21), random.randrange(0, 59), random.randrange(0, 59))
	inputTimeString = inputTime.strftime('%H:%M:%S')
	f.write("('" + str(oId) + "', '0', '" + inputTimeString + "', '" + inputDateString + "');\n")
	#oId +=1	

	f.write("INSERT INTO Customer_Order_Details (menu_item, order_number, quantity) VALUES ")
	for i in range(oId-799, oId):
		orderType = random.randrange(0, 14)
		menuItemString = []
		menuItemStringQuant = []
		if orderType == 0:
			menuItemString.append("Cheeseburger")
			menuItemString.append("3 Chicken Tenders")
			menuItemStringQuant.append("2")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			#f.write("UPDATE Customer_Orders SET TotalCost = '18.77' WHERE CustomerID = '" + str(oId) + "';\n")
			orderTypeList.append(orderType)
		elif orderType == 1:
			menuItemString.append("Aggie Chicken Club")
			menuItemString.append("French Fries")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("2")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			#f.write("UPDATE Customer_Orders SET TotalCost = '12.37' WHERE CustomerID = '" + str(oId) + "';\n")
			orderTypeList.append(orderType)
		elif orderType == 2:
			menuItemString.append("Cheeseburger")
			menuItemString.append("French Fries")
			menuItemString.append("Vanilla Aggie Shake")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			#f.write("UPDATE Customer_Orders SET TotalCost = '13.37' WHERE CustomerID = '" + str(oId) + "';\n")
			orderTypeList.append(orderType)
		elif orderType == 3:
			menuItemString.append("Tuna Melt")
			menuItemString.append("Root Beer Float")
			menuItemString.append("Fish Sandwich")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			orderTypeList.append(orderType)
		elif orderType == 4:
			menuItemString.append("Black Bean Burger")
			menuItemString.append("Chicken Caesar Salad")
			menuItemString.append("20 OZ Aquafina Water")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			orderTypeList.append(orderType)
		elif orderType == 5:
			menuItemString.append("Gig Em Patty Melt")
			menuItemString.append("Sugar Cookie Oreo Cookie Ice Cream Sundae")
			menuItemString.append("Revs Grilled Chicken Sandwich")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			orderTypeList.append(orderType)
		elif orderType == 6:
			menuItemString.append("20 OZ Fountain Drink")
			menuItemString.append("2 Corn Dogs")
			menuItemString.append("Strawberry Aggie Shake")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			orderTypeList.append(orderType)
		elif orderType == 7:
			menuItemString.append("16 OZ Aquafina Water")
			menuItemString.append("Spicy Chicken Sandwich")
			menuItemString.append("1 Chicken Bacon Ranch Wrap")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			orderTypeList.append(orderType)
		elif orderType == 8:
			menuItemString.append("Oreo Cookie Double Scoop Ice Cream")
			menuItemString.append("Vanilla Double Scoop Ice Cream")
			menuItemString.append("Strawberry Double Scoop Ice Cream")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			orderTypeList.append(orderType)
		elif orderType == 9:
			menuItemString.append("Chocolate Double Scoop Ice Cream")
			menuItemString.append("Chocolate Chip Cookie Oreo Cookie Ice Cream Sundae")
			menuItemString.append("Chocolate Chip Cookie Vanilla Ice Cream Sundae")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			orderTypeList.append(orderType)
		elif orderType == 10:
			menuItemString.append("Chocolate Chip Cookie Strawberry Ice Cream Sundae")
			menuItemString.append("Chocolate Chip Cookie Chocolate Ice Cream Sundae")
			menuItemString.append("Sugar Cookie Vanilla Ice Cream Sundae")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			orderTypeList.append(orderType)
		elif orderType == 11:
			menuItemString.append("Sugar Cookie Strawberry Ice Cream Sundae")
			menuItemString.append("Sugar Cookie Chocolate Ice Cream Sundae")
			menuItemString.append("Oreo Cookie Aggie Shake")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			orderTypeList.append(orderType)
		elif orderType == 12:
			menuItemString.append("Chocolate Aggie Shake")
			menuItemString.append("1 Classic Chicken Wrap")
			menuItemString.append("2 Classic Chicken Wraps")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			orderTypeList.append(orderType)
		elif orderType == 13:
			menuItemString.append("2 Chicken Bacon Ranch Wraps")
			menuItemString.append("2 Hot Dogs")
			menuItemString.append("Classic Hamburger")
			menuItemString.append("Bacon Cheeseburger")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			f.write("('" + str(menuItemString[3]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[3]) + "'),\n")
			orderTypeList.append(orderType)

	
	orderType = random.randrange(0, 14)
	menuItemString = []
	menuItemStringQuant = []
	if orderType == 0:
		menuItemString.append("Cheeseburger")
		menuItemString.append("3 Chicken Tenders")
		menuItemStringQuant.append("2")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[1]) + "');\n")
		#f.write("UPDATE Customer_Orders SET TotalCost = '18.77' WHERE CustomerID = '" + str(oId) + "';\n")
		orderTypeList.append(orderType)
	elif orderType == 1:
		menuItemString.append("Aggie Chicken Club")
		menuItemString.append("French Fries")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("2")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[1]) + "');\n")
		#f.write("UPDATE Customer_Orders SET TotalCost = '12.37' WHERE CustomerID = '" + str(oId) + "';\n")
		orderTypeList.append(orderType)
	elif orderType == 2:
		menuItemString.append("Cheeseburger")
		menuItemString.append("French Fries")
		menuItemString.append("Vanilla Aggie Shake")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[2]) + "');\n")
		#f.write("UPDATE Customer_Orders SET TotalCost = '13.37' WHERE CustomerID = '" + str(oId) + "';\n")
		orderTypeList.append(orderType)
	elif orderType == 3:
		menuItemString.append("Tuna Melt")
		menuItemString.append("Root Beer Float")
		menuItemString.append("Fish Sandwich")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[2]) + "');\n")
		orderTypeList.append(orderType)
	elif orderType == 4:
		menuItemString.append("Black Bean Burger")
		menuItemString.append("Chicken Caesar Salad")
		menuItemString.append("20 OZ Aquafina Water")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[2]) + "');\n")
		orderTypeList.append(orderType)
	elif orderType == 5:
		menuItemString.append("Gig Em Patty Melt")
		menuItemString.append("Sugar Cookie Oreo Cookie Ice Cream Sundae")
		menuItemString.append("Revs Grilled Chicken Sandwich")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[2]) + "');\n")
		orderTypeList.append(orderType)
	elif orderType == 6:
		menuItemString.append("20 OZ Fountain Drink")
		menuItemString.append("2 Corn Dogs")
		menuItemString.append("Strawberry Aggie Shake")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[2]) + "');\n")
		orderTypeList.append(orderType)
	elif orderType == 7:
		menuItemString.append("16 OZ Aquafina Water")
		menuItemString.append("Spicy Chicken Sandwich")
		menuItemString.append("1 Chicken Bacon Ranch Wrap")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[2]) + "');\n")
		orderTypeList.append(orderType)
	elif orderType == 8:
		menuItemString.append("Oreo Cookie Double Scoop Ice Cream")
		menuItemString.append("Vanilla Double Scoop Ice Cream")
		menuItemString.append("Strawberry Double Scoop Ice Cream")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[2]) + "');\n")
		orderTypeList.append(orderType)
	elif orderType == 9:
		menuItemString.append("Chocolate Double Scoop Ice Cream")
		menuItemString.append("Chocolate Chip Cookie Oreo Cookie Ice Cream Sundae")
		menuItemString.append("Chocolate Chip Cookie Vanilla Ice Cream Sundae")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[2]) + "');\n")
		orderTypeList.append(orderType)
	elif orderType == 10:
		menuItemString.append("Chocolate Chip Cookie Strawberry Ice Cream Sundae")
		menuItemString.append("Chocolate Chip Cookie Chocolate Ice Cream Sundae")
		menuItemString.append("Sugar Cookie Vanilla Ice Cream Sundae")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[2]) + "');\n")
		orderTypeList.append(orderType)
	elif orderType == 11:
		menuItemString.append("Sugar Cookie Strawberry Ice Cream Sundae")
		menuItemString.append("Sugar Cookie Chocolate Ice Cream Sundae")
		menuItemString.append("Oreo Cookie Aggie Shake")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[2]) + "');\n")
		orderTypeList.append(orderType)
	elif orderType == 12:
		menuItemString.append("Chocolate Aggie Shake")
		menuItemString.append("1 Classic Chicken Wrap")
		menuItemString.append("2 Classic Chicken Wraps")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[2]) + "');\n")
		orderTypeList.append(orderType)
	elif orderType == 13:
		menuItemString.append("2 Chicken Bacon Ranch Wraps")
		menuItemString.append("2 Hot Dogs")
		menuItemString.append("Classic Hamburger")
		menuItemString.append("Bacon Cheeseburger")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
		f.write("('" + str(menuItemString[3]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[3]) + "');\n")
		orderTypeList.append(orderType)

	f.write("INSERT INTO Customer_Orders (order_number, total_cost, order_time, order_date) VALUES ")
	for i in range(0, 799):
		inputDate = datetime.date(2023, 8, 25)
		inputDateString = inputDate.strftime('%Y-%m-%d')
		inputTime = datetime.time(random.randrange(8, 21), random.randrange(0, 59), random.randrange(0, 59))
		inputTimeString = inputTime.strftime('%H:%M:%S')
		f.write("('" + str(oId+1) + "', '0', '" + inputTimeString + "', '" + inputDateString + "'),\n")
		oId +=1

	inputDate = datetime.date(2023, 8, 25)
	inputDateString = inputDate.strftime('%Y-%m-%d')
	inputTime = datetime.time(random.randrange(8, 21), random.randrange(0, 59), random.randrange(0, 59))
	inputTimeString = inputTime.strftime('%H:%M:%S')
	f.write("('" + str(oId+1) + "', '0', '" + inputTimeString + "', '" + inputDateString + "');\n")
	oId +=1	

	f.write("INSERT INTO Customer_Order_Details (menu_item, order_number, quantity) VALUES ")
	for i in range(oId-799, oId):
		orderType = random.randrange(0, 14)
		menuItemString = []
		menuItemStringQuant = []
		if orderType == 0:
			menuItemString.append("Cheeseburger")
			menuItemString.append("3 Chicken Tenders")
			menuItemStringQuant.append("2")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			#f.write("UPDATE Customer_Orders SET TotalCost = '18.77' WHERE CustomerID = '" + str(oId) + "';\n")
			orderTypeList.append(orderType)
		elif orderType == 1:
			menuItemString.append("Aggie Chicken Club")
			menuItemString.append("French Fries")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("2")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			#f.write("UPDATE Customer_Orders SET TotalCost = '12.37' WHERE CustomerID = '" + str(oId) + "';\n")
			orderTypeList.append(orderType)
		elif orderType == 2:
			menuItemString.append("Cheeseburger")
			menuItemString.append("French Fries")
			menuItemString.append("Vanilla Aggie Shake")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			#f.write("UPDATE Customer_Orders SET TotalCost = '13.37' WHERE CustomerID = '" + str(oId) + "';\n")
			orderTypeList.append(orderType)
		elif orderType == 3:
			menuItemString.append("Tuna Melt")
			menuItemString.append("Root Beer Float")
			menuItemString.append("Fish Sandwich")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			orderTypeList.append(orderType)
		elif orderType == 4:
			menuItemString.append("Black Bean Burger")
			menuItemString.append("Chicken Caesar Salad")
			menuItemString.append("20 OZ Aquafina Water")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			orderTypeList.append(orderType)
		elif orderType == 5:
			menuItemString.append("Gig Em Patty Melt")
			menuItemString.append("Sugar Cookie Oreo Cookie Ice Cream Sundae")
			menuItemString.append("Revs Grilled Chicken Sandwich")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			orderTypeList.append(orderType)
		elif orderType == 6:
			menuItemString.append("20 OZ Fountain Drink")
			menuItemString.append("2 Corn Dogs")
			menuItemString.append("Strawberry Aggie Shake")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			orderTypeList.append(orderType)
		elif orderType == 7:
			menuItemString.append("16 OZ Aquafina Water")
			menuItemString.append("Spicy Chicken Sandwich")
			menuItemString.append("1 Chicken Bacon Ranch Wrap")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			orderTypeList.append(orderType)
		elif orderType == 8:
			menuItemString.append("Oreo Cookie Double Scoop Ice Cream")
			menuItemString.append("Vanilla Double Scoop Ice Cream")
			menuItemString.append("Strawberry Double Scoop Ice Cream")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			orderTypeList.append(orderType)
		elif orderType == 9:
			menuItemString.append("Chocolate Double Scoop Ice Cream")
			menuItemString.append("Chocolate Chip Cookie Oreo Cookie Ice Cream Sundae")
			menuItemString.append("Chocolate Chip Cookie Vanilla Ice Cream Sundae")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			orderTypeList.append(orderType)
		elif orderType == 10:
			menuItemString.append("Chocolate Chip Cookie Strawberry Ice Cream Sundae")
			menuItemString.append("Chocolate Chip Cookie Chocolate Ice Cream Sundae")
			menuItemString.append("Sugar Cookie Vanilla Ice Cream Sundae")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			orderTypeList.append(orderType)
		elif orderType == 11:
			menuItemString.append("Sugar Cookie Strawberry Ice Cream Sundae")
			menuItemString.append("Sugar Cookie Chocolate Ice Cream Sundae")
			menuItemString.append("Oreo Cookie Aggie Shake")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			orderTypeList.append(orderType)
		elif orderType == 12:
			menuItemString.append("Chocolate Aggie Shake")
			menuItemString.append("1 Classic Chicken Wrap")
			menuItemString.append("2 Classic Chicken Wraps")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			orderTypeList.append(orderType)
		elif orderType == 13:
			menuItemString.append("2 Chicken Bacon Ranch Wraps")
			menuItemString.append("2 Hot Dogs")
			menuItemString.append("Classic Hamburger")
			menuItemString.append("Bacon Cheeseburger")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			menuItemStringQuant.append("1")
			f.write("('" + str(menuItemString[0]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
			f.write("('" + str(menuItemString[1]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
			f.write("('" + str(menuItemString[2]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
			f.write("('" + str(menuItemString[3]) + "', '" + str(i) + "', '" + str(menuItemStringQuant[3]) + "'),\n")
			orderTypeList.append(orderType)


	
	orderType = random.randrange(0, 14)
	menuItemString = []
	menuItemStringQuant = []
	if orderType == 0:
		menuItemString.append("Cheeseburger")
		menuItemString.append("3 Chicken Tenders")
		menuItemStringQuant.append("2")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[1]) + "');\n")
		#f.write("UPDATE Customer_Orders SET TotalCost = '18.77' WHERE CustomerID = '" + str(oId) + "';\n")
		orderTypeList.append(orderType)
	elif orderType == 1:
		menuItemString.append("Aggie Chicken Club")
		menuItemString.append("French Fries")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("2")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[1]) + "');\n")
		#f.write("UPDATE Customer_Orders SET TotalCost = '12.37' WHERE CustomerID = '" + str(oId) + "';\n")
		orderTypeList.append(orderType)
	elif orderType == 2:
		menuItemString.append("Cheeseburger")
		menuItemString.append("French Fries")
		menuItemString.append("Vanilla Aggie Shake")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[2]) + "');\n")
		#f.write("UPDATE Customer_Orders SET TotalCost = '13.37' WHERE CustomerID = '" + str(oId) + "';\n")
		orderTypeList.append(orderType)
	elif orderType == 3:
		menuItemString.append("Tuna Melt")
		menuItemString.append("Root Beer Float")
		menuItemString.append("Fish Sandwich")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[2]) + "');\n")
		orderTypeList.append(orderType)
	elif orderType == 4:
		menuItemString.append("Black Bean Burger")
		menuItemString.append("Chicken Caesar Salad")
		menuItemString.append("20 OZ Aquafina Water")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[2]) + "');\n")
		orderTypeList.append(orderType)
	elif orderType == 5:
		menuItemString.append("Gig Em Patty Melt")
		menuItemString.append("Sugar Cookie Oreo Cookie Ice Cream Sundae")
		menuItemString.append("Revs Grilled Chicken Sandwich")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[2]) + "');\n")
		orderTypeList.append(orderType)
	elif orderType == 6:
		menuItemString.append("20 OZ Fountain Drink")
		menuItemString.append("2 Corn Dogs")
		menuItemString.append("Strawberry Aggie Shake")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[2]) + "');\n")
		orderTypeList.append(orderType)
	elif orderType == 7:
		menuItemString.append("16 OZ Aquafina Water")
		menuItemString.append("Spicy Chicken Sandwich")
		menuItemString.append("1 Chicken Bacon Ranch Wrap")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[2]) + "');\n")
		orderTypeList.append(orderType)
	elif orderType == 8:
		menuItemString.append("Oreo Cookie Double Scoop Ice Cream")
		menuItemString.append("Vanilla Double Scoop Ice Cream")
		menuItemString.append("Strawberry Double Scoop Ice Cream")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[2]) + "');\n")
		orderTypeList.append(orderType)
	elif orderType == 9:
		menuItemString.append("Chocolate Double Scoop Ice Cream")
		menuItemString.append("Chocolate Chip Cookie Oreo Cookie Ice Cream Sundae")
		menuItemString.append("Chocolate Chip Cookie Vanilla Ice Cream Sundae")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[2]) + "');\n")
		orderTypeList.append(orderType)
	elif orderType == 10:
		menuItemString.append("Chocolate Chip Cookie Strawberry Ice Cream Sundae")
		menuItemString.append("Chocolate Chip Cookie Chocolate Ice Cream Sundae")
		menuItemString.append("Sugar Cookie Vanilla Ice Cream Sundae")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[2]) + "');\n")
		orderTypeList.append(orderType)
	elif orderType == 11:
		menuItemString.append("Sugar Cookie Strawberry Ice Cream Sundae")
		menuItemString.append("Sugar Cookie Chocolate Ice Cream Sundae")
		menuItemString.append("Oreo Cookie Aggie Shake")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[2]) + "');\n")
		orderTypeList.append(orderType)
	elif orderType == 12:
		menuItemString.append("Chocolate Aggie Shake")
		menuItemString.append("1 Classic Chicken Wrap")
		menuItemString.append("2 Classic Chicken Wraps")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[2]) + "');\n")
		orderTypeList.append(orderType)
	elif orderType == 13:
		menuItemString.append("2 Chicken Bacon Ranch Wraps")
		menuItemString.append("2 Hot Dogs")
		menuItemString.append("Classic Hamburger")
		menuItemString.append("Bacon Cheeseburger")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		menuItemStringQuant.append("1")
		f.write("('" + str(menuItemString[0]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[0]) + "'),\n")
		f.write("('" + str(menuItemString[1]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[1]) + "'),\n")
		f.write("('" + str(menuItemString[2]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[2]) + "'),\n")
		f.write("('" + str(menuItemString[3]) + "', '" + str(oId) + "', '" + str(menuItemStringQuant[3]) + "');\n")
		orderTypeList.append(orderType)


	#Updates order number total prices
	f.write("UPDATE Customer_Orders SET total_cost = '18.77' WHERE order_number = ")
	for i in range(0, len(orderTypeList)):
		if orderTypeList[i] == 0:
			f.write(str(i+1) + " OR order_number =")
	f.write("-1;\n")

	f.write("UPDATE Customer_Orders SET total_cost = '12.37' WHERE order_number = ")
	for i in range(0, len(orderTypeList)):
		if orderTypeList[i] == 1:
			f.write(str(i+1) + " OR order_number =")
	f.write("-1;\n")

	f.write("UPDATE Customer_Orders SET total_cost = '13.37' WHERE order_number = ")
	for i in range(0, len(orderTypeList)):
		if orderTypeList[i] == 2:
			f.write(str(i+1) + " OR order_number =")
	f.write("-1;\n")

	f.write("UPDATE Customer_Orders SET total_cost = '21.47' WHERE order_number = ")
	for i in range(0, len(orderTypeList)):
		if orderTypeList[i] == 3:
			f.write(str(i+1) + " OR order_number =")
	f.write("-1;\n")

	f.write("UPDATE Customer_Orders SET total_cost = '18.07' WHERE order_number = ")
	for i in range(0, len(orderTypeList)):
		if orderTypeList[i] == 4:
			f.write(str(i+1) + " OR order_number =")
	f.write("-1;\n")

	f.write("UPDATE Customer_Orders SET total_cost = '20.67' WHERE order_number = ")
	for i in range(0, len(orderTypeList)):
		if orderTypeList[i] == 5:
			f.write(str(i+1) + " OR order_number =")
	f.write("-1;\n")

	f.write("UPDATE Customer_Orders SET total_cost = '11.67' WHERE order_number = ")
	for i in range(0, len(orderTypeList)):
		if orderTypeList[i] == 6:
			f.write(str(i+1) + " OR order_number =")
	f.write("-1;\n")
	
	f.write("UPDATE Customer_Orders SET total_cost = '13.67' WHERE order_number = ")
	for i in range(0, len(orderTypeList)):
		if orderTypeList[i] == 7:
			f.write(str(i+1) + " OR order_number =")
	f.write("-1;\n")

	f.write("UPDATE Customer_Orders SET total_cost = '9.87' WHERE order_number = ")
	for i in range(0, len(orderTypeList)):
		if orderTypeList[i] == 8:
			f.write(str(i+1) + " OR order_number =")
	f.write("-1;\n")

	f.write("UPDATE Customer_Orders SET total_cost = '12.67' WHERE order_number = ")
	for i in range(0, len(orderTypeList)):
		if orderTypeList[i] == 9:
			f.write(str(i+1) + " OR order_number =")
	f.write("-1;\n")

	f.write("UPDATE Customer_Orders SET total_cost = '14.07' WHERE order_number = ")
	for i in range(0, len(orderTypeList)):
		if orderTypeList[i] == 10:
			f.write(str(i+1) + " OR order_number =")
	f.write("-1;\n")

	f.write("UPDATE Customer_Orders SET total_cost = '13.87' WHERE order_number = ")
	for i in range(0, len(orderTypeList)):
		if orderTypeList[i] == 11:
			f.write(str(i+1) + " OR order_number =")
	f.write("-1;\n")

	f.write("UPDATE Customer_Orders SET total_cost = '12.48' WHERE order_number = ")
	for i in range(0, len(orderTypeList)):
		if orderTypeList[i] == 12:
			f.write(str(i+1) + " OR order_number =")
	f.write("-1;\n")

	f.write("UPDATE Customer_Orders SET total_cost = '26.17' WHERE order_number = ")
	for i in range(0, len(orderTypeList)):
		if orderTypeList[i] == 13:
			f.write(str(i+1) + " OR order_number =")
	f.write("-1;\n")